### ISSUE TITLE
Change keyboard (inputType) on the fly

### ISSUE THREAD

**Issue by frogermcs** [AzimoLabs/MaskFormatter#2]
MaskFormatter should update keyboard type (number/text) on the fly, depending on currently given mask char.

**Comment by mbozetka** [comment]
Done.

**Comment by hipczor** [comment]
This should be configurable.

I have `%%% %%% %%%` mask just to format 9 randomly generated chars to be more readable. When I enter for example `FXG H33 44W`, mask formatter always goes back to INPUT_TYPE_TEXT, and I have to switch back to number keyboard after every digit.
